// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissionFour.Models;

namespace MissionFour.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220127044530_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MissionFour.Models.movieEntry", b =>
                {
                    b.Property<int>("movieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("movieID");

                    b.ToTable("entry");

                    b.HasData(
                        new
                        {
                            movieID = 1,
                            category = "Action",
                            director = "Jim Hentsen",
                            edited = false,
                            rating = "PG-13",
                            title = "Winter Soilder",
                            year = (short)2016
                        },
                        new
                        {
                            movieID = 2,
                            category = "Action",
                            director = "Jim Hentsen",
                            edited = false,
                            rating = "PG-13",
                            title = "Civil War",
                            year = (short)2019
                        },
                        new
                        {
                            movieID = 3,
                            category = "Action",
                            director = "Jim Hentsen",
                            edited = false,
                            rating = "PG-13",
                            title = "End Game",
                            year = (short)2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
